import 'package:flutter_login_signup/models/courses_model.dart';



class HigherEducation {
  String imageUrl;
  String name;
  String type;
  List<String> startTimes;
  int rating;
  int price;
  List<Course> courses;

  HigherEducation({
    this.imageUrl,
    this.name,
    this.type,
    this.startTimes,
    this.rating,
    this.price,
    this.courses,
  });
}

List<HigherEducation> higherEducations = [
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Boston College',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Witwatersrand University',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),

  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Rosebank College',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),

  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'University Of Pretoria',
    type: 'We empower people',
    startTimes: ['11 April', '18 July'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/murano.jpg',
    name: 'University Of Johannesburg',
    type: 'Solutions For Africa',
    startTimes: ['11 April', '18 June'],
    rating: 3,
    price: 125,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'North West University',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Monash University',
    type: 'We empower people',
    startTimes: ['11 April', '18 June'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Limpopo',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'University Of Venda',
    type: 'We empower people',
    startTimes: ['11 April', '18 June'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Free State',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Central University of Technology',
    type: 'We empower people',
    startTimes: ['11 April', '18 June'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Mpumalanga',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Northen Cape',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 June'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Cape Town',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'University Of Western Cape',
    type: 'We empower people',
    startTimes: ['11 April', '18 June'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Stellenbosch University',
    type: 'Solutions For Africa',
    startTimes: ['11 April', '18 July'],
    rating: 3,
    price: 125,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Cape Peninsula University Of Technology',
    type: 'Solutions For Africa',
    startTimes: ['11 April', '18 July'],
    rating: 3,
    price: 125,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Rhodes University',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 June'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Nelson Mandela Metropolitan University',
    type: 'We empower people',
    startTimes: ['11 April', '18 July'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Walter Sisulu University',
    type: 'Solutions For Africa',
    startTimes: ['11 April', '18 June'],
    rating: 3,
    price: 125,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/murano.jpg',
    name: 'University Of Fort Hare',
    type: 'Solutions For Africa',
    startTimes: ['11 April', '18 June'],
    rating: 3,
    price: 125,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'University Of Kwazulu Natal',
    type: 'Knowledge and work',
    startTimes: ['11 April', '18 July'],
    rating: 5,
    price: 100,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Durban University of Technology',
    type: 'We empower people',
    startTimes: ['11 April', '18 June'],
    rating: 4,
    price: 210,
    courses: courses,
  ),
  HigherEducation(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'University of Zululand',
    type: 'We empower people',
    startTimes: ['11 April', '18 July'],
    rating: 4,
    price: 210,
    courses: courses,)
];

List<Course> courses = [
  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'B.Sc Medical Sciences',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Business Management',
    type: 'We empower people',
    startTimes: ['3 years', '18 July'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Optometry',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Communication & Media Studies',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Computer Science',
    type: 'We empower people',
    startTimes: ['3 years', '18 June'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Chemical Engineering',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Forensic Science',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 July'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Geology',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Medicine',
    type: 'We empower people',
    startTimes: ['3 years', '18 June'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Nursing',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Psychology',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Social Work',
    type: 'We empower people',
    startTimes: ['3 years', '18 June'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Veterinary Medicine',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Music',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Pharmacology',
    type: 'We empower people',
    startTimes: ['3 years', '18 June'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Pharmacy',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Physics & Astronomy',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),

  Course(
    imageUrl: 'assets/images/stmarksbasilica.jpg',
    name: 'Agriculture & Forestry',
    type: 'Knowledge and work',
    startTimes: ['4 years', '18 June'],
    rating: 5,
    price: 15000,
  ),
  Course(
    imageUrl: 'assets/images/gondola.jpg',
    name: 'Architecture',
    type: 'We empower people',
    startTimes: ['3 years', '18 June'],
    rating: 4,
    price: 21000,
  ),
  Course(
    imageUrl: 'assets/images/murano.jpg',
    name: 'Celtic Studies',
    type: 'Solutions For Africa',
    startTimes: ['3 years', '18 June'],
    rating: 3,
    price: 12500,
  ),
];